networks:
  ticket-booking-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: ticket-booking-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ticket_booking
      MYSQL_PASSWORD: password
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--skip-character-set-client-handshake"
    volumes:
      - ./data/db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3336:3306"
    networks:
      - ticket-booking-network

  redis:
    image: redis:7
    container_name: ticket-booking-redis
    ports:
      - "6399:6379"
    networks:
      - ticket-booking-network
